# Generated by Django 5.1.3 on 2024-11-29 22:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Comunas',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Regiones',
            },
        ),
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio', models.DecimalField(decimal_places=0, max_digits=10)),
                ('tipo', models.CharField(choices=[('casa', 'Casa'), ('departamento', 'Departamento'), ('sitio', 'Sitio'), ('bodega', 'Bodega'), ('espacio_seguro', 'Espacio Seguro'), ('estacionamiento', 'Estacionamiento'), ('oficina', 'Oficina')], max_length=20)),
                ('metros_construidos', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('metros_terreno', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('habitaciones', models.IntegerField(default=0)),
                ('banos', models.IntegerField(default=0)),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('comuna', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='propiedapp.comuna')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='propiedapp.region')),
            ],
        ),
        migrations.AddField(
            model_name='comuna',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comunas', to='propiedapp.region'),
        ),
        migrations.AlterUniqueTogether(
            name='comuna',
            unique_together={('nombre', 'region')},
        ),
    ]
